### PR TITLE
Add enableAutoTrackingIP & disableAutoTrackingIP

### PR DESCRIPTION
**Pull request by tung-vu-td**
New feature:
- `enableAutoTrackingIP` will tell TD backend to add `td_ip` column with the device ip
- `disableAutoTrackingIP` will disable this behavior.

Note: IP is tracked at the request level. Which means the IP address is the one when `uploadEvents` is called.

### CODE REVIEW

**Review by kietdo360 — APPROVED** [review]
LGTM

**Comment by kietdo360** [comment]
Still LGTM

**Review by imnutz — APPROVED** [review]
LGTM

**Review by nmpennypacker — APPROVED** [review]
Reviewed for data exfiltrations

**Pull request merged**
