### PR TITLE
A New Swift SDK!

### PR DESCRIPTION
**Pull request by uny**
I have implemented a new SDK in Swift.
This has beautiful swifty syntax and is well-tested.
Could you accept it as the next major version SDK for this repository? or may I release it as another SDK?

### CODE REVIEW

**Comment by uny** [comment]
@komamitsu 
How do you like it?

**Comment by komamitsu** [comment]
@uny Wow, really great work...

I discussed with co-workers about it and concluded it's a bit difficult for now to maintain the Swift version source codes and documents in addition to the current Objective-C version. So we'd like to propose you to release it as another SDK.

Please let us know when you release it. We'll add a link to it on our document with pleasure :)

**Comment by uny** [comment]
We released:
https://github.com/recruit-lifestyle/TreasureDataSDK

**Comment by komamitsu** [comment]
Thanks. I added the link to our documents https://docs.treasuredata.com/articles/ios-sdk#alternatives and https://github.com/treasure-data/td-ios-sdk/commit/4204d393d9822b5a02f56e973841224fff129953

**Comment by uny** [comment]
Thank you!
When you can, we would like to maintain this with you in this organization.
This PR can be closed now.

**Comment by cezheng** [comment]
Maybe a bit late to join the discussion, just want to speak out what it think.

## Swift has bad binary compatibility
Swift's syntax is not stable yet, and newer versions binary is not compatible with that of older versions, which makes it hard to distribute the SDK as a prebuilt framework, leaving it unusable for developers who can not use Cocoapods/Carthage for some specific reasons.

## The Swift implementation depends on Realm\
https://github.com/recruit-lifestyle/TreasureDataSDK/blob/master/Cartfile
Realm is a great DB for mobile apps, which I have been using on personal projects. Not sure if a lightweight log collecting SDK should have dependencies like this. When I integrated the td-ios-sdk for some C++ based game apps, I was impressed by the current implementation that is so simple and standalone: no specific linker flags, no external dependencies, just add the binary and link with it then it's done.

**Comment by huylenq** [comment]
The Swift SDK fell behind in several features, and it seems that we concluded it should be released and develop separately, then I'll close this for now.

**Pull request closed without merging**
